# Generated by Django 4.0.4 on 2022-04-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=222, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
            preserve_default=False,
        ),
    ]
