# Generated by Django 4.0.4 on 2022-04-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_item_order_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
            preserve_default=False,
        ),
    ]
