# Generated by Django 4.0.4 on 2022-04-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
    ]
