# Generated by Django 4.0.4 on 2022-04-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
            preserve_default=False,
        ),
    ]
