# Generated by Django 4.0.4 on 2022-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_item_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(default=666, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, help_text='Paste here the item link from its official shop', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='metric_unit',
            field=models.CharField(blank=True, choices=[('KG', 'kg'), ('G', 'g'), ('LB', 'lb')], default='KG', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'unpaid'), (3, 'paid'), (4, 'shipped'), (5, 'delivering'), (6, 'recieved')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='track_code',
            field=models.CharField(default=777, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
