# Generated by Django 4.0.4 on 2022-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_options_item_address_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=666, max_length=100),
            preserve_default=False,
        ),
    ]
