# Generated by Django 4.0.4 on 2022-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_item_address_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='metric_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb')], default='kg', max_length=2, null=True),
        ),
    ]
