# Generated by Django 4.0.4 on 2022-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_item_metric_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='metric_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound')], default='kg', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivering', 'Delivering'), ('recieved', 'Recieved')], default='new', max_length=10),
        ),
    ]
