# Generated by Django 4.0.4 on 2022-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_item_metric_unit_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='metric_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb')], default='kg', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
