# Generated by Django 4.0.4 on 2022-05-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_order_status_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
