# Generated by Django 4.0.4 on 2022-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_order_track_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('unpaid', 'unpaid'), ('paid', 'paid'), ('shipped', 'shipped'), ('delivering', 'delivering'), ('recieved', 'recieved')], default='new', max_length=10),
        ),
    ]
