# Generated by Django 4.0.4 on 2022-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('₺', '₺'), ('som', 'som')], default='$', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ready', 'ready'), ('paid', 'paid'), ('shipped', 'shipped'), ('delivering', 'delivering'), ('recieved', 'recieved')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
