# Generated by Django 4.0.4 on 2022-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_item_cost_alter_order_cost_alter_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('₺', '₺'), ('som', 'som')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, help_text='Paste here the link of an item or an item photo', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='metric_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb')], default='kg', max_length=2),
        ),
    ]
