# Generated by Django 4.0.4 on 2022-05-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_item_currency_alter_item_link_alter_item_metric_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='no comment yet', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ready', 'ready'), ('paid', 'paid'), ('shipped', 'shipped'), ('arrived', 'arrived'), ('delivering', 'delivering'), ('recieved', 'recieved')], default='new', max_length=20),
        ),
    ]
