# Generated by Django 4.0.4 on 2022-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_order_comment_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='metric_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb')], default='g', max_length=2),
        ),
    ]
